---
name: App-ZofCMS-Plugin-HTMLFactory-PageToBodyId
version: 0.0102
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to automatically create id="" attributes on <body> depending on the current page
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0111
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::HTMLFactory::PageToBodyId:
    file: lib/App/ZofCMS/Plugin/HTMLFactory/PageToBodyId.pm
    version: 0.0102
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
