---
abstract: "plugin to automatically create id=\"\" attributes on <body> depending on the current page"
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-HTMLFactory-PageToBodyId
provides:
  App::ZofCMS::Plugin::HTMLFactory::PageToBodyId:
    file: lib/App/ZofCMS/Plugin/HTMLFactory/PageToBodyId.pm
    version: 0.0103
requires:
  App::ZofCMS: 0.0111
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
